desafio-ror/config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :products
  resources :posts
  resources :navbars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

desafio-ror/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

desafio-ror/app/models/navbar.rb
class Navbar < ApplicationRecord
end

desafio-ror/app/models/post.rb
class Post < ApplicationRecord
end

desafio-ror/app/models/product.rb
class Product < ApplicationRecord
end

desafio-ror/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :set_locale

def set_locale
    I18n.locale = 'es'
    @navbars = Navbar.all
end
end

desafio-ror/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @post = Post.last
  end
end

desafio-ror/app/controllers/navbars_controller.rb
class NavbarsController < ApplicationController
  before_action :set_navbar, only: %i[ show edit update destroy ]

  # GET /navbars or /navbars.json
  def index
    @navbars = Navbar.all
  end

  # GET /navbars/1 or /navbars/1.json
  def show
  end

  # GET /navbars/new
  def new
    @navbar = Navbar.new
  end

  # GET /navbars/1/edit
  def edit
  end

  # POST /navbars or /navbars.json
  def create
    @navbar = Navbar.new(navbar_params)

    respond_to do |format|
      if @navbar.save
        format.html { redirect_to navbar_url(@navbar), notice: "Navbar was successfully created." }
        format.json { render :show, status: :created, location: @navbar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @navbar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /navbars/1 or /navbars/1.json
  def update
    respond_to do |format|
      if @navbar.update(navbar_params)
        format.html { redirect_to navbar_url(@navbar), notice: "Navbar was successfully updated." }
        format.json { render :show, status: :ok, location: @navbar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @navbar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navbars/1 or /navbars/1.json
  def destroy
    @navbar.destroy

    respond_to do |format|
      format.html { redirect_to navbars_url, notice: "Navbar was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_navbar
      @navbar = Navbar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def navbar_params
      params.require(:navbar).permit(:label, :url)
    end
end

desafio-ror/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:imagen, :title, :content)
    end
end

desafio-ror/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:imagen, :title, :description)
    end
end

desafio-ror/app/helpers/application_helper.rb
module ApplicationHelper
end

desafio-ror/app/helpers/home_helper.rb
module HomeHelper
end

desafio-ror/app/helpers/navbars_helper.rb
module NavbarsHelper
end

desafio-ror/app/helpers/posts_helper.rb
module PostsHelper
end

desafio-ror/app/helpers/products_helper.rb
module ProductsHelper
end

desafio-ror/app/views/home/index.html.erb
<section id="media-object">
		<div class="container">
					<div class="product-img">
						<%= image_tag @post.imagen, :class => "img-media" %> 
					</div>
					<div class="text-media">
						<h2><%= @post.title%> </h2>
						<div class="text-large">
							<%= @post.content%> 
						</div>
	
					</div>
		
        </div>
	</section>
	<section class="product-cards">
		<div class="container">
			<div class="product-card">
				<% @products.each do |product| %>
					<div class="product-img">
						<%= image_tag product.imagen, :class => "product-img" %> 
					</div>
					<div class="product-description">
						<h3><%= product.title%> </h3>
					</div>
					<div class="product-footer">
						<div class="puntuation">
							<i class="fa fa-star" aria-hidden="true"></i>	
							<i class="fa fa-star" aria-hidden="true"></i>
							<i class="fa fa-star" aria-hidden="true"></i>
							<i class="fa fa-star" aria-hidden="true"></i>
							<i class="fa fa-star-half-o" aria-hidden="true"></i>
						</div>
						<div class="details">
							<p><%= product.description%></p>
							<button class = "order"><i class="fa fa-cart-plus" aria-hidden="true"></i></button>
						</div>
					</div>
				<% end %>
				
			</div>
		</div>
	</section>

desafio-ror/app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>DESAFIO HTML + CSS</title>
	<link rel="stylesheet" type="text/css" href="estilo.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
	<header>
		<div id="banner">
		</div>
		<nav class="navbar">
			<div class="navbar-links">
				<ul>
					<% @navbars.each do |navbar| %>
					<li><%= link_to navbar.label, navbar.url %> </li>
					<% end %>
				</ul>
			</div>
		</nav>
	</header>
	
</body>
</html>

desafio-ror/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

desafio-ror/app/views/navbars/_form.html.erb
<%= simple_form_for(@navbar) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :label, label: t('navbars.label')%>
    <%= f.input :url, label: t('navbars.url') %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, t('common.save'), :class => "btn btn-primary"%>
  </div>
<% end %>
</div

desafio-ror/app/views/navbars/_navbar.html.erb
<div id="<%= dom_id navbar %>">
  <p>
    <strong>Label:</strong>
    <%= navbar.label %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= navbar.url %>
  </p>

</div>

desafio-ror/app/views/navbars/edit.html.erb
<div class="form-new">
  <div class="input-form">
    <h1>Editing navbar</h1>

    <%= render "form", navbar: @navbar %>

    <br>

    <div>
      <%= button_to t('common.show'), @navbar, :class => "btn btn-primary" %> |
      <%= button_to t('common.back'), navbars_path, :class => "btn btn-primary" %>
    </div>
  </div>
</div>

desafio-ror/app/views/navbars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Navbar</h1>

<table class="table">
    <thead>
      <tr>
        <th scope="col"><%= t('navbars.url') %></th>
        <th scope="col"><%= t('navbars.label') %></th>
      </tr>
      <tbody>
          <% @navbars.each do |navbar| %>
          <tr>
            <div id="<%= dom_id navbar %>">
            <td> <%= navbar.url %></td>
            <td><%= navbar.label %></td>
            <td> <%= link_to t('common.show'), navbar %> </td>
          </tr>
          <% end %>
      </tbody>
      </div>
    </table>


<%= link_to t('common.new'), new_navbar_path %>
</div>

desafio-ror/app/views/navbars/new.html.erb
<div class="form-new">
  <div class="input-form">
    <h1>Nuevo Navbar</h1>

    <%= render "form", navbar: @navbar %>
    <br>

    <div>
      <%= link_to t('common.back'), navbars_path %>
    </div>
  </div>
</div>

desafio-ror/app/views/navbars/show.html.erb
<div class="form-new">
  <div class="input-form">
    <p style="color: green"><%= notice %></p>

    <%= render @navbar %>

    <div>
      <%= link_to t('common.edit'), edit_navbar_path(@navbar) %> |
      <%= link_to t('common.back'), navbars_path %>

      <%= button_to t('common.destroy'), @navbar, method: :delete %>
    </div>
  </div>
</div>

desafio-ror/app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :imagen , label: t('posts.imagen')%>
    <%= f.input :title, label: t('posts..title')%>
    <%= f.input :content, label: t('posts.content') %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, t('common.save')  %>
  </div>
<% end %>

desafio-ror/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong><%= t('posts.imagen') %>:</strong>
    <%= post.imagen %>
  </p>

  <p>
    <strong><%= t('posts.title') %></strong>
    <%= post.title %>
  </p>

  <p>
    <strong><%= t('posts.content') %></strong>
    <%= post.content %>
  </p>

</div>

desafio-ror/app/views/posts/edit.html.erb
<div class="form-new">
  <div class="input-form">
    <h1><%= t('common.editing_title')%></h1>

    <%= render "form", post: @post %>

    <br>

    <div>
      <%= link_to t('common.show'), @post %> |
      <%= link_to t('common.back'), posts_path %>
    </div>
  </div>
</div>

desafio-ror/app/views/posts/index.html.erb
<div class="form-new">
  <div class="input-form">
    <p style="color: green"><%= notice %></p>

    <h1>Posts</h1>
    <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= t('posts.imagen') %></th>
        <th scope="col"><%= t('posts.title') %></th>
        <th scope="col"><%= t('posts.content') %></th>
      </tr>
      <tbody>
          <% @posts.each do |post| %>
          <tr>
            <div id="<%= dom_id post %>">
            <td> <%= post.imagen %></td>
            <td><%= post.title %></td>
            <td><%= post.content %></td>
            <td> <%= link_to t('common.show'), post %> </td>
          </tr>
          <% end %>
      </tbody>
      </div>
    </table>

    <%= link_to t('common.new'), new_post_path %>
  </div>
</div>

desafio-ror/app/views/posts/new.html.erb
<div class="form-new">
  <div class="input-form">
    <h1><%= t('posts.new_post')%></h1>

    <%= render "form", post: @post %>

    <br>

    <div>
      <%= link_to t('common.back'), posts_path %>
    </div>
  </div>
</div>

desafio-ror/app/views/posts/show.html.erb
<div class="form-new">
  <div class="input-form">
    <p style="color: green"><%= notice %></p>

    <%= render @post %>

    <div>
      <%= link_to t('common.edit'), edit_post_path(@post) %> |
      <%= link_to t('common.back'), posts_path %>

      <%= button_to t('common.destroy'), @post, method: :delete %>
    </div>
  </div>
</div>

desafio-ror/app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :imagen, label: t('products.imagen') %>
    <%= f.input :title, label: t('products.title') %>
    <%= f.input :description, label: t('products.description') %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, t('common.save') %>
  </div>
<% end %>

desafio-ror/app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong><%= t('products.imagen') %></strong>
    <%= product.imagen %>
  </p>

  <p>
    <strong><%= t('products.title') %></strong>
    <%= product.title %>
  </p>

  <p>
    <strong><%= t('products.description') %></strong>
    <%= product.description %>
  </p>

</div>

desafio-ror/app/views/products/edit.html.erb
<div class="form-new">
  <div class="input-form">
    <h1><%= t('common.editing_title')%> |</h1>

    <%= render "form", product: @product %>

    <br>

    <div>
      <%= link_to t('common.show'), @product %> |
      <%= link_to t('common.back'), products_path %>
    </div>
   </div>
</div>

desafio-ror/app/views/products/index.html.erb
<div class="form-new">
  <div class="input-form">
    <p style="color: green"><%= notice %></p>

    <h1><%= t('common.new')%></h1>

    <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= t('products.imagen') %></th>
        <th scope="col"><%= t('products.title') %></th>
        <th scope="col"><%= t('products.description') %></th>
      </tr>
      <tbody>
          <% @products.each do |product| %>
          <tr>
            <div id="<%= dom_id product %>">
            <td> <%= product.imagen %></td>
            <td><%= product.title %></td>
            <td><%= product.description %></td>
            <td> <%= link_to t('common.show'), product %> </td>
          </tr>
          <% end %>
      </tbody>
      </div>
    </table>


    <%= link_to t('common.new'), new_product_path%>

  </div>
</div>

desafio-ror/app/views/products/new.html.erb
<div class="form-new">
  <div class="input-form">
    <h1><%= t('common.new')%> </h1>

    <%= render "form", product: @product %>

    <br>

    <div>
      <%= link_to t('common.back'), products_path %>
    </div>
  </div>
</div>

desafio-ror/app/views/products/show.html.erb
<div class="form-new">
  <div class="input-form">
    <p style="color: green"><%= notice %></p>

    <%= render @product %>

    <div>
      <%= link_to t('common.edit'), edit_product_path(@product) %> |
      <%= link_to t('common.back'), products_path %>

      <%= button_to t('common.destroy'), @product, method: :delete %>
    </div>
  </div>
</div>